last_updated = "2025-12-22T14:44:46Z"

[[contracts]]
name = "Market"
package_name = "Market"
package_hash = "hash-412764be7266d8431b5381ca1cbf840dbb93640ccc1b5c0393e40eb3c4aae519"

[[contracts]]
name = "FaucetableWcspr"
package_name = "FaucetableWcspr"
package_hash = "hash-6c09a60d42b35329f20941bceb4bdb5b2104dd96ad2ff608b2784bef2c71a3f0"

[[contracts]]
name = "PositionToken"
package_name = "CD_SHORT"
package_hash = "hash-48f1fe2756bd9d66b1102c58e87a9ca6b2e33990571d9904b71c39df72417d11"

[[contracts]]
name = "PositionToken"
package_name = "CD_LONG"
package_hash = "hash-226ef7940f010c57dcc2dd1e7d8c06e126472e28a11319aec8cd8d56bad162cb"
